### ISSUE TITLE
1D scores don't work?

### ISSUE THREAD

**Issue by Phlya** [nezar-compbio/lavaburst#2]
Hi Nezar,

How to use lavaburst with 1D scores, such as directionality index or insulation score?
Trying simply this, same as for potts/armatus/corner scores doesn't work:

```
chr19 = completeIC(serum10K.matrix().fetch('chr19').toarray())
S = scoring.insul(chr19)
model = segment.SegModel(S)
segments = model.optimal_segmentation()
```

I get this:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-40-222e428fbaf6> in <module>()
----> 1 S = scoring.insul(chr19)
      2 model = segment.SegModel(S)
      3 segments = model.optimal_segmentation()

/usr/local/lib/python3.4/dist-packages/lavaburst/scoring.py in insul(A, extent)
    146         ri, rj = where_diagonal(A, k)
    147         for i in range(0, N-k+1):
--> 148             score[i+k] = A[ri[i:i+k], rj[i:i+k]]
    149     return score
    150 

ValueError: setting an array element with a sequence.

```

And with all other functions - this:

```
ValueError                                Traceback (most recent call last)
<ipython-input-42-bada6283fa82> in <module>()
      1 S = scoring.insul_diamond(chr19)
      2 model = segment.SegModel(S)
----> 3 segments = model.optimal_segmentation()

/usr/local/lib/python3.4/dist-packages/lavaburst/segment.py in optimal_segmentation(self, return_score, maxsize, gapped)
     25 
     26         """
---> 27         opt, pred = max_sum(self.score_matrix)
     28         path = get_path(opt, pred)
     29         if self.edgemask is not None:

lavaburst/core/segment.pyx in lavaburst.core.segment.max_sum (lavaburst/core/segment.c:1860)()

ValueError: Buffer has wrong number of dimensions (expected 2, got 1)
```

Should they be used somehow completely differently?

**Comment by nvictus** [comment]
Hey Ilya,

Yes, you're right! The 1D scores are just an extra utility and should be moved to a different module: lavaburst needs a matrix of scores. Howeve, you use the 1D tracks to call boundaries by using a peak finder, like `scipy.signal.find_peaks_cwt`, but @golobor recommends another peak finder called peakdet, which I haven't tried yet, but he might be able to point you to it.

**Comment by Phlya** [comment]
Hi Nezar,

Thanks, that makes sense! I'll try it then. Seems like peakdet is here, considering there is a comment by @golobor https://gist.github.com/endolith/250860#file-peakdetect-py

**Comment by Phlya** [comment]
Bu just `insul` doesn't work at all, actually, I showed the error in the first post here.

**Comment by nvictus** [comment]
1D scores are now in [cooltools](https://github.com/mirnylab/cooltools)
