### ISSUE TITLE
python3 import broken?

### ISSUE THREAD

**Issue by Phlya** [nezar-compbio/lavaburst#3]
Hi, maybe I am being stupid, but I can't import `segment` in python3... This is all I get:

```
s1529682:~$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from lavaburst import scoring, segment, sampling, utils
>>> 
[4]+  Stopped                 python
s1529682:~$ python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from lavaburst import scoring, segment, sampling, utils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'segment'
>>> 
[5]+  Stopped                 python3

```
The same code works fine in python2. In both versions lavaburst installed using pip from the repo.
Am I missing something?

**Comment by Phlya** [comment]
Tried installing anew on a different computer (our cluster, actually), same thing on python3...

**Comment by nvictus** [comment]
The `segment` module is deprecated. `SegModel` is now a top-level import. Sorry for not documenting the change!

**Comment by Phlya** [comment]
All right, thanks!

**Comment by Phlya** [comment]
Just curious, why does it work in pyhton2 then?..

**Comment by nvictus** [comment]
Ha, beats me! My best guess is that it's lingering bytecode (.pyc files) from an earlier installation. I just tried installing on a fresh 2.7 environment and `from lavaburst import segment` fails.

**Comment by Phlya** [comment]
I see! I think I had it installed on py2, but installed it fresh on py3 now, so could be. Thanks!
