### ISSUE TITLE
ImportError: cannot import name 'segment'

### ISSUE THREAD

**Issue by guo-ya** [nezar-compbio/lavaburst#4]
Hi Nezar,
I try to run the example, but shows:

![lavaburst_segment_and_sampling](https://user-images.githubusercontent.com/19996201/32138963-0131ce74-bc35-11e7-8b58-e4f14001e314.png)

So whether lavaburst (v0.2.0) contains segment and sampling? How can I use lavaburst's segment and sampling?

Thanks a lot!

**Comment by nvictus** [comment]
The `segment` and `sampling` modules were replaced with `model`, but the `SegModel` class is now a top level export, so you can just import `SegModel` directly from `lavaburst`.

**Comment by nvictus** [comment]
The example notebook was updated, so I'm going to close this.
